mybatis:
  mapper-locations: classpath:mapper/*.xml
  #type-aliases-package: com.demo.pojo
spring:
  datasource:
    username: root
    password: 159357
    url: jdbc:mysql://localhost:3306/test?useUnicode=true
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8081
  servlet:
    context-path: /boot